### PR TITLE
HOLD - LDAP to AD migration changes

### PR DESCRIPTION
**Pull request by ericras**
ldaps://unl.edu/
cn=its-cms,ou=service,dc=unl,dc=edu

### CODE REVIEW

**Comment by nbarry10** [comment]
We noticed several LDAP attribute name changes, like uid.  We haven't started any work on our stuff yet, but if you ldap bind to uid, it might not work...

**Comment by ericras** [comment]
I have it working with adtest (which isn't reflected in the comment or code; what is here should be production ready)

I don't know that https://unl.app.box.com/notes/280966064225?s=1mtr3o3usqsd0hfgknkeab2xidxhvebd is entirely accurate; for instance i don't think it is ever 'mail' and I used 'unlmail' instead

**Comment by nbarry10** [comment]
Good to know, cause we saw that same document.  I'll also ask IDM if I run into any of them about the discrepancies.

**Comment by ericras** [comment]
eb8240fd38d78e62e73973cd869b82ed783533fe

**Pull request closed without merging**
